### ISSUE TITLE
nodejs underscore

### ISSUE THREAD

**Issue by xoxo111** [xoxo111/xoxo111#1]
Hello Guys,

I tried to install underscore with the command line
npm install -g underscore  and it says that 1package is there.

After I try this command line:
node name.js it says that underscore cant be found
Need help.

**Comment by xoxo111** [comment]
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Node\fractal_server.js:10:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
